name: unit test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 22.x]

    steps:
    - uses: actions/checkout@v4
    - uses: actions/cache@v4.0.2
      id: cache-npm
      with: 
       path: ~/.npm
       key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
       restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-    

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      
      with:
        node-version: ${{ matrix.node-version }}

    - name: Build
      run: |
        npm install
        npx test
